### ISSUE TITLE
[Feat] 회원 관리 기능에 대한 구상

### ISSUE THREAD

**Issue by SongGwanSeok** [Co-due/Code-Analysis-Server#40]
## 📝 Description
**무엇을?**
- 회원 관리 기능에 대해 고민하고 정리한다

**왜?**
- 회원 관리 기능 구현

## ❗️Todo
- [ ] 회원 관리 기능을 구현하기 위해 필요한 기술 정의
- [ ] 필요한 기술에 대한 공부
- [ ] 회원 관리의 전체적인 구상 정리

## ETC
기타사항
